#!/bin/bash

echo "🚀 EduVerse AI - Railway Deployment Checklist"
echo "=============================================="
echo ""
echo "✅ Step 1: Initialize Git Repository"
echo "   git init"
echo "   git add ."
echo "   git commit -m 'Initial commit - EduVerse AI Backend'"
echo ""
echo "✅ Step 2: Create GitHub Repository"
echo "   - Go to github.com/new"
echo "   - Create repository: eduverse-backend"
echo "   - Copy the repository URL"
echo ""
echo "✅ Step 3: Push to GitHub"
echo "   git remote add origin <your-repo-url>"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "✅ Step 4: Deploy on Railway"
echo "   1. Visit: https://railway.app"
echo "   2. Click 'New Project'"
echo "   3. Select 'Deploy from GitHub repo'"
echo "   4. Choose: eduverse-backend"
echo ""
echo "✅ Step 5: Add PostgreSQL Database"
echo "   1. Click 'New' in Railway project"
echo "   2. Select 'Database' → 'PostgreSQL'"
echo "   3. Copy DATABASE_URL"
echo ""
echo "✅ Step 6: Configure Environment Variables"
echo "   Add these in Railway Variables:"
echo "   - DATABASE_URL (from PostgreSQL service)"
echo "   - SECRET_KEY (generate strong key)"
echo "   - ALGORITHM=HS256"
echo "   - ACCESS_TOKEN_EXPIRE_MINUTES=60"
echo ""
echo "✅ Step 7: Generate Domain"
echo "   Settings → Generate Domain"
echo ""
echo "✅ Step 8: Test Deployment"
echo "   Visit: https://your-app.up.railway.app/health"
echo ""
echo "🎉 Deployment Complete!"
